### ISSUE TITLE
Add quick fixes for unmapped target properties

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct-idea#1]

**Comment by filiphr** [comment]
Renamed this to be quick fixes for unmapped target properties. For the second quick fix in Eclipse see https://github.com/mapstruct/mapstruct-idea/issues/25.

This has already been done in https://github.com/mapstruct/mapstruct-idea/commit/5b2e545774a140ee65054f1c2d36cc8d6dd56dbf
