### ISSUE TITLE
Support chained mapping composition

### ISSUE THREAD

**Issue by thunderhook** [mapstruct/mapstruct-idea#129]
I already thought of implementing the support of mapping composition in the IntelliJ plugin but waited for it to leave the experimental state.

Here it is: https://github.com/mapstruct/mapstruct/issues/3239

Therefore i would implement this feature after #65

**Comment by filiphr** [comment]
Thanks @thunderhook

**Comment by filiphr** [comment]
Fixed with PR #134. Thanks @thunderhook. Just FYI, I changed the title since this was about supporting chained mapping composition
