### ISSUE TITLE
java.lang.ClassCastException: Object of type Address can't be cast to CompositeTracker

### ISSUE THREAD

**Issue by Serkan80** [mapstruct/mapstruct-idea#147]
Hi,

I'm migrating from Quarkus 2.16.7 to Quarkus 3.2.0 and I'm using MapStruct 1.5.5 and from the migration guide of Quarkus I read that I've to change the componentModel from CDI to JAKARTA and this is somehow not working.

I get the following error:
`java.lang.ClassCastException: Object of type 'class Address' can't be cast to CompositeTracker`.

And here is my mapping:

```java

import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;

import java.time.OffsetDateTime;

import static io.quarkus.runtime.util.StringUtil.isNullOrEmpty;
import static org.mapstruct.MappingConstants.ComponentModel.JAKARTA;

@Mapper(componentModel = JAKARTA)
public interface MyMapper {

    MyDto toDto(MyEntity entity);

    MyEntity toEntity(MyDto request);

    void updateEntity(MyDto dto, @MappingTarget MyEntity entity);

    default OffsetDateTime toOffsetDateTime(String date) {
        return isNullOrEmpty(date) ? null : OffsetDateTime.parse(date, FORMATTER);
    }
}

```

And the mapper that gets generated looks fine imho:

```java

import jakarta.inject.Named;
import jakarta.inject.Singleton;
import javax.annotation.processing.Generated;  --> shouldn't this also start with jakarta ??

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-07-07T11:43:15+0200",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 17.0.5 (Eclipse Adoptium)"
)
@Singleton
@Named
public class MyMapperImpl implements MyMapper {
 ...// nothing fancy here
}
```

I've also tried `JAKARTA_CDI` as component model, but I still get the same error.

And this used to work in Quarkus 2.16.7...

**Comment by filiphr** [comment]
@Serkan80 you've opened an issue in the IntelliJ plugin for MapStruct. I don't see how this is related.

Also  from your examples I do not see how MapStruct could be causing a problem. It looks like some kind of a runtime error.

And for your comment "shouldn't this also start with jakarta ??", not it shouldn't the `javax.annotation.processing.Generated` annotation is part of the `java.compile` module.
