### ISSUE TITLE
Fix workaround for getting the mockJDK annotations.jar in the gradle build

### ISSUE THREAD

**Issue by thunderhook** [mapstruct/mapstruct-idea#157]
Currently we use a workaround, using a a tag version link to get the mockJDK `annotations.jar` since it was removed in the master branch.

e.g.:
https://github.com/JetBrains/intellij-community/raw/212.5712/java/mockJDK-11/jre/lib/annotations.jar
instead of
https://github.com/JetBrains/intellij-community/raw/master/java/mockJDK-11/jre/lib/annotations.jar

Maybe [this commit](https://github.com/JetBrains/intellij-community/commit/aa6829d7c1a80a3b6b805a942d5e11c89c3432c3#diff-f43cd6af045f66a855be140a772e86898b5f20368d73b297ad93e339d3b031ec) can help to understand why it happened, and what is needed to get it up and running again.

**Comment by filiphr** [comment]
Good point @thunderhook. Perhaps we need to look into and see if we can avoid using the mock jdks as well, or perhaps it is even the time to drop testing with older JDKs
