### ISSUE TITLE
Code completion doesn't work with lombok @SuperBuilder annotation

### ISSUE THREAD

**Issue by PyotrSpetsnaz** [mapstruct/mapstruct-idea#159]
### Plugin Information
- Plugin Version: 1.6.1
- Mapstruct Version: 1.5.5
- Lombok Version: 1.18.28
- Java Version: 17
- IDE Version: Intellij IDEA Ultimate 2023.2.5

### Problem Description
The code completion feature of the MapStruct Support plugin is not working properly when using the lombok `@SuperBuilder` (`lombok.experimental.SuperBuilder`) annotation.

### Steps to Reproduce
1. Create a new Java class.
2. Add the lombok `@SuperBuilder` annotation to the class.
3. Try to use code completion for any field in `@Mapper` annotation. 

### Expected Behavior
When using the `@SuperBuilder` annotation, the code completion feature should suggest the available fields.

### Actual Behavior
The code completion feature does not suggest any fields or methods.

### Screenshots and Code Snippets
```java
// Class with annotation
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
public class Builder {
    private Integer bar;
}
```
```java
// Class without annotation
@Getter
@Setter
public class WithoutBuilder {
    private Integer foo;
    private Builder innerBuilder; // To show that autocompletion works for inner builders
}
```
```java
// Mapper with broken code completion
@Mapper
public interface BuilderMapper {
    @Mapping(target = "", source = "")
    Builder map(WithoutBuilder builder);
}
```
Doesn't work for class with `@SuperBuilder`:
<img width="293" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/29255419/cfe18fd6-2f57-4ac7-aa1c-105aaf392129">
But works for class without `@SuperBuilder`:
<img width="532" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/29255419/e185abf7-7196-48ee-b425-ec1fc33658bb">
Even works for class with `@SuperBuilder` which inside a class without `@SuperBuilder`:
<img width="447" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/29255419/8958ae76-76bf-47a0-a635-4ff8d8c10d20">

### Additional Information
Generated class for `@Mapping(target = "bar", source = "foo")` to show that it is valid mapper:
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-11-13T17:06:33+0700",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 17.0.8 (BellSoft)"
)
public class BuilderMapperImpl implements BuilderMapper {

    @Override
    public Builder map(WithoutBuilder builder) {
        if ( builder == null ) {
            return null;
        }

        Builder builder1 = new Builder();

        builder1.setBar( builder.getFoo() );

        return builder1;
    }
}

```

**Comment by thunderhook** [comment]
Yes you're right. A minified reproducal without lombok:

```java

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

class SuperBuilderTarget {

    private Integer bar;

    protected SuperBuilderTarget(SuperBuilderTargetBuilder<?, ?> b) {
        this.bar = b.bar;
    }

    public static SuperBuilderTargetBuilder<?, ?> builder() {
        return new SuperBuilderTargetBuilderImpl();
    }

    public static abstract class SuperBuilderTargetBuilder<C extends SuperBuilderTarget, B extends SuperBuilderTargetBuilder<C, B>> {
        private Integer bar;

        public B bar(Integer bar) {
            this.bar = bar;
            return self();
        }

        protected abstract B self();

        public abstract C build();

        public String toString() {
            return "SuperBuilderTarget.SuperBuilderTargetBuilder(bar=" + this.bar + ")";
        }
    }

    private static final class SuperBuilderTargetBuilderImpl
        extends SuperBuilderTargetBuilder<SuperBuilderTarget, SuperBuilderTargetBuilderImpl> {
        private SuperBuilderTargetBuilderImpl() {
        }

        protected SuperBuilderTargetBuilderImpl self() {
            return this;
        }

        public SuperBuilderTarget build() {
            return new SuperBuilderTarget( this );
        }
    }
}

class Source {
    public Integer foo;
}

@Mapper
interface BuilderMapper {
    @Mapping(target = "", source = "foo")  
    SuperBuilderTarget map(Source builder);
}
```

First quick analysis shows that [this](https://github.com/mapstruct/mapstruct-idea/blob/main/src/main/java/org/mapstruct/intellij/util/MapstructUtil.java#L212) evaluates to `false` when the `bar(...)` method is picked, therefore this is ignored.

**Comment by filiphr** [comment]
We don't support Lombok `@SuperBuilder` in MapStruct. The example is a bit confusing because the target type is also called `Builder`.

If you look at the generated code you'll see that it is calling the setter on your target type

```java
builder1.setBar( builder.getFoo() );
```

I would say the bug is that the plugin even tries to use the builder for the detection
