### ISSUE TITLE
Auto-completion doesn't work for public fields

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct-idea#16]
If I map into public fields (instead of property setters), auto-completion isn't working in the IntelliJ plug-in.

**Comment by filiphr** [comment]
That is true. Currently, only getters / setters are used for autocompletion. We need to support public fields as well

**Comment by torsten-github** [comment]
Same for unmapped inspection warnings when a getter/setter is mapped to a public field.

Thanks for the great work :)

**Comment by filiphr** [comment]
Done as part of https://github.com/mapstruct/mapstruct-idea/pull/40
