### ISSUE TITLE
Completion for properties don't work (both target and source)

### ISSUE THREAD

**Issue by swetharnaik** [mapstruct/mapstruct-idea#172]
I have installed the Mapstruct Support plugin 1.6.1 in my IDE IntelliJ 2023.3.2. I am using Java 11 as mentioned in the README.

There are suggested actions for adding target mappings as shown in the screenshot below.
<img width="779" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/17508164/9fc2255b-3325-4c19-82b5-e3fdc2a1ad75">

But the suggestions for source or taget properties/fields are not present (attached screenshot below). Am I missing something here? Are there any known restrictions for the plugin?
I would like to contribute a fix if it isn't complicated.
<img width="542" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/17508164/a1a33af8-4d02-471e-ba92-31f8921b1e1e">

For simplicity, I kept the fields of `DesDto` and `SourceDto` public. Also generated the getters and setters as well.

<img width="497" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/17508164/a8877cea-3773-4459-9754-382c2b9818b7">
<img width="454" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/17508164/a68d5b21-94ca-455b-a664-5d64af779ceb">

**Comment by thunderhook** [comment]
Hey @swetharnaik!

Thanks for the report. I tried to reproduce it with the exact same code, but for me, the auto-completion does work 🤔 

This seems like a possible issue with your IntelliJ. Please try to use all steps from the action `Repair IDE` and tell me if this worked for you.

Just for reference, I tried it with the following version (`Help > About > Copy and Close)`:
```
IntelliJ IDEA 2023.3.2 (Community Edition)
Build #IC-233.13135.103, built on December 20, 2023
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  nl.bryanderidder.regexrenamefiles (1.2.6)
  idea.plugin.protoeditor (233.13135.65)
  com.jetbrains.edu (2023.11-2023.3-421)
  DevKit (233.13135.104)
  Lombook Plugin (233.13135.65)
  org.jetbrains.idea.grammar (2022.3.2)
  com.jetbrains.packagesearch.intellij-plugin (233.11799.196)
  PythonCore (233.13135.103)
  org.asciidoctor.intellij.asciidoc (0.41.6)
  org.mapstruct.intellij (1.6.1)
Kotlin: 233.13135.103-IJ
```

**Comment by filiphr** [comment]
Closing this due to lack of response. @swetharnaik please let us know if you still have issues with this and we can reopen it.
