### ISSUE TITLE
code wraps automatically, does not recognize keywords

### ISSUE THREAD

**Issue by Muscleape** [mapstruct/mapstruct-idea#184]
When displayed on one line, it is recognized normally, but the keyword is not recognized when changing lines

<img width="1016" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/16682039/b371be43-0b76-4449-a811-1dc28b24f90d">

<img width="872" alt="image" src="https://github.com/mapstruct/mapstruct-idea/assets/16682039/145d0599-225a-4a16-97c2-7b93e2946cae">

**Comment by filiphr** [comment]
Closing this since we already have #82 and #98 for this.
