### ISSUE TITLE
Code completion: mapTo... suggestions take precedence over more useful suggestions

### ISSUE THREAD

**Issue by kalvintamas** [mapstruct/mapstruct-idea#190]
When I invoke code completion (or the popup opens automatically as I write) there are always tons of mapper methods on top. This is annoying because I rarely use these mapper suggestions, I usually write/call them directly.

I didn't find a way to disable this in mapstruct, inspection, or other settings. But I don't want to disable/uninstall the plugin because it is helpful when writing mapstruct mappers.

Is there any method to disable these? Or could you implement it?

![image](https://github.com/mapstruct/mapstruct-idea/assets/61846148/035592f2-8ba0-4eec-b880-1ad633c8adad)

**Comment by thunderhook** [comment]
Hi @kalvintamas 

Thanks for reaching out. 

What code completions do you mean exactly with `mapTo...` suggestions? Do you mean the code completion of `source`, `target` and `qualifiedByName` inside `@Mapping`?

Yes, we can add a setting which disables code completion, but still provides the references.

Technical note for my future self or the one implementing it:
`return LookupElement.EMPTY_ARRAY` in `getVariantsInternal(PsiMethod)` while leaving the code as is in `getVariantsInternal(PsiType)`.

**Comment by kalvintamas** [comment]
I edited the original post by adding a screenshot for clarification.

**Comment by thunderhook** [comment]
Thanks for the clarification.
These code suggestions are not coming from the MapStruct plugin. It must be another plugin.

There is nothing we can do about it. You can find the culprit by disabling some plugins. It would be good to know what caused this.
Maybe you can give some insight when you find out.

I will close this topic for now. If it is still related to the mapstruct plugin, we can reopen it.

**Comment by kalvintamas** [comment]
Thank you for your help. Could you maybe suggest me where to turn for help? Is this build-in IntelliJ feature?

**Comment by thunderhook** [comment]
Unfortunately not. I don't get these auto-completion suggestions with my Ultimate license.

If I were you, I would disable some plugins in `Settings > Plugins` or even use the `Disable all downloaded plugins` option there. Then see if it still happens and maybe raise an IntelliJ YouTrack issue.

**Comment by kalvintamas** [comment]
Thanks for your tip!

Actually I found the plugin responsible for this. It was JPA Buddy, and unfortunately, it doesn't have an option to disable only the mapTo... suggestions, you can only disable every smart code completion that comes from that plugin. Maybe if I contact them they can do something about it.
