### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by aRusenov** [mapstruct/mapstruct-idea#20]
Currently the plugin only works in .java @Mapper classes (though it offers completions for _source_ and _target_ when referencing Kotlin classes as well!). It seems as if the plugin is simply not triggered in .kt mappers, but it works otherwise fine with Kotlin. 

Kotlin Mapper interface:
![Kotlin](https://image.ibb.co/cPyucb/kt.png)

Java Mapper interface:
![Java](https://image.ibb.co/jhWKAw/java.png)

In both cases the DTO and model are Kotlin classes.

Versions used:
- Kotlin 1.1.51
- mapstruct 1.2.0.final
- IntelliJ Community Edition 2017.2.3

**Comment by filiphr** [comment]
The plugin uses the default way of accessing the annotations in elements. I have to dig in to understand how it works within kotlin. If someone has some idea or knows what exactly needs to be done I am looking forward to your help 😄

**Comment by lppedd** [comment]
@filiphr I can have a look at it, I want to keep using Kotlin and completion is always helpful. Could you maybe point the a starting point (such as a specific class)?

**Comment by filiphr** [comment]
One starting point would be [Handling code]( https://www.jetbrains.org/intellij/sdk/docs/tutorials/kotlin.html#handling-kotlin-code) from the IntelliJ SDK documentation.

As for the plugin some starting classes that you would need to look are:

```
<psi.referenceContributor language="JAVA" implementation="org.mapstruct.intellij.codeinsight.references.MapstructReferenceContributor" />
<methodReferencesSearch implementation="org.mapstruct.intellij.search.MappingMethodUsagesSearcher" />
<renameHandler implementation="org.mapstruct.intellij.rename.MapstructSourceTargetParameterRenameHandler"/>
```

The way the completion works is by providing references through a reference contributor. The `MapstructReferenceContributor` is the one that registers the contributors. I think that you can actually use the same implementation, but you would need to provide different `MapstructElementUtils` that would be able to get the `PsiElement` from the kotlin plugin.

The `MappingMethodUsagesSearcher` is something I needed to add for find usages to work. Maybe it would work ootb with Kotlin, as I don't see anything specific to Java in there.

The `MapstructSourceTargetParameterRenameHandler` is something I needed to add for renaming to work properly, I think that we can reuse that as well, but we would need to find a neat way to pass `MAPPING_SOURCE_OR_TARGET` as the Kotlin plugin dependency should be optional.

There are some tests, that might guide you and that you might be able to utilise for debugging

**Comment by greenarr0w** [comment]
Are there any news on this issue? It would be very nice to have kotlin support.

**Comment by filiphr** [comment]
@greenarr0w I haven't had a lot of time to look into this. If someone from the community would like to step up and help with this it would be much appreciated.

**Comment by filiphr** [comment]
Done in https://github.com/mapstruct/mapstruct-idea/commit/41dd19040264c64effb63b5148fc462da791af0c and https://github.com/mapstruct/mapstruct-idea/commit/1119db7cdb94d088e7e0ed59b7ac36e7ae9e757f

thanks @ifrankwang for your work on this.
