### ISSUE TITLE
Expression can not get method hint when target uses @Lombok @FieldNameConstants

### ISSUE THREAD

**Issue by Ben901227** [mapstruct/mapstruct-idea#205]
### Expected behavior

![image](https://github.com/user-attachments/assets/41addb7b-74c0-406e-8b7a-5b0d89a15062)
When I use a fixed String(`modifyDate`) to declare the target, I can see the hint in expression `getDate()` and the default method `getDate()` is 1 usage.

### Actual behavior

![image](https://github.com/user-attachments/assets/912859fe-a2d2-4908-9d50-f05311f29b2e)
When I use @Lombok @FieldNameConstants define `modifyDate` to declare the target, I can not see the hint in expression `getDate()` and the default method `getDate()` became no usages .

### Steps to reproduce the problem

my mapping configuration
```gradle
    implementation 'org.mapstruct:mapstruct:1.6.0'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0"
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.0'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
```
BaseMap
```java
@Mapper
public interface BaseMap {

    BaseMap INSTANCE = Mappers.getMapper( BaseMap.class );

    @Mapping(target = BaseEntity.BaseFields.modifyDate, expression = "java(getDate())")
    BaseDTO toBaseDto(BaseEntity baseEntity);

    default Date getDate() {
        return new Date();
    }
}
```

BaseDTO

```java
@Data
@FieldNameConstants
public class BaseDTO {
    private Date modifyDate;
}
```

### MapStruct Version

MapStruct 1.6.0

**Comment by thunderhook** [comment]
Hi @Ben901227, thanks for reaching out!

This is an issue of the mapstruct-idea plugin, so I moved the issue to this repository.

After a quick debugging session it seems that the following IDEA internal class does not resolve the reference: 
* [`ReferenceProvidersRegistry.getReferencesFromProviders( attributeValue )`](https://github.com/mapstruct/mapstruct-idea/blob/e0586d7f5b6efde0afae1631201e4a473c5b2682/src/main/java/org/mapstruct/intellij/expression/JavaExpressionInjector.java#L176)

As far as I know, there is nothing we can do, maybe raise an issue in the IDEA YouTrack itself?
@hduelme do you have any idea on how (or if) we can fix this?

**Comment by filiphr** [comment]
@thunderhook have you tried with `@Mappings(@Mapping(target = BaseDTO.Fields.modifyDate, expression = "java(getDate())")`? If you read the docs for [`FieldNameConstants`](https://projectlombok.org/features/experimental/FieldNameConstants) you'll see that there is a technical limitation and they don't work with MapStruct.

>MapStruct interop: When making references to field name constants inside MapStruct's `@Mapping`, and you use that annotation more than once on a node, you must manually wrap these in the `@Mappings` 'container annotation'. Like so: `@Mappings({@Mapping(target = Entity.Fields.entityProperty, source = "dtoProperty")})`.

In any case, I would not spend time on fixing problems with experimental Lombok features such as `FieldNameConstants`. Therefore, I'm closing this.

**Comment by Ben901227** [comment]
Yes, I tried `@Mappings(@Mapping(target = BaseDTO.Fields.modifyDate, expression = "java(getDate())")` as well, but it's still not working. 
Thank you for your assistance. I will look for other workarounds.
