### ISSUE TITLE
When using Lombok in @Mapping's target, the expression field will lose the reference relationship 

### ISSUE THREAD

**Issue by 183461750** [mapstruct/mapstruct-idea#206]
Screenshots of lost reference relationships :
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/89bd9de4-ba0c-479d-9a63-fca6c07342a8">

Screenshots with reference relationships :
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/50762a04-872b-4a75-8eb8-79ef3cc0086f">

The expectation is that when used together with Lombok, the reference relationship can also be used normally. 

Thank you !

**Comment by filiphr** [comment]
@183461750 The use of field extensions might be the cause why this is not working. That is something experimental from Lombok and we are not going to spend the effort in supporting it.

I would advise that you use regular string int he `target` and `source`.
