### ISSUE TITLE
Unmapped target properties

### ISSUE THREAD

**Issue by lvcyong** [mapstruct/mapstruct-idea#21]
Warning:java: Unmapped target properties: "wzdm, dl, tempid, usernameCreate, userCreate".

**Comment by filiphr** [comment]
@lvcyong I don't understand what you mean with this issue.

Can you please clarify?

If you are referring from the compiler output that you get this comes from the Java Annotation Processor running the Mapstruct processor and it seems you have unmapped target properties.

**Comment by l0co** [comment]
How to disable this warning?

**Comment by filiphr** [comment]
@l0co are you referring to the compilation warning?

This is not linked with the IntelliJ plugin. You have multiple options to avoid this:

* [`Mapper#unmappedTargetPolicy`](http://mapstruct.org/documentation/stable/api/org/mapstruct/Mapper.html#unmappedTargetPolicy--)
* Explicitly ignore properties via `@Mapping(target = "something", ignore = true)`

**Comment by filiphr** [comment]
Have you read about the [Configuration options](http://mapstruct.org/documentation/stable/reference/html/#configuration-options) in our documentation? You can disable them via a compiler option. However, I strongly advise against using the compiler option. I always advise to explicitly define what you need  too map

**Comment by l0co** [comment]
I overlooked these options, thanks!

**Comment by l0co** [comment]
Heh, it looks in java 10 the compiler option causes another warning (both gradle and Idea):

```
Information:javac 10 was used to compile java sources
Information:10.05.18 09:08 - Compilation completed successfully with 1 warning in 3s 64ms
Warning:java: The following options were not recognized by any processor: '[mapstruct.unmappedTargetPolicy]'
```

**Comment by filiphr** [comment]
We haven't really tested MapStruct with Java 10, but it should work. Are you still getting the unmapped target properties, or not?

**Comment by l0co** [comment]
> Are you still getting the unmapped target properties, or not?

With `-Amapstruct.unmappedTargetPolicy=IGNORE` there's no more errors about unmapped properties. However there's persistent `The following options were not recognized by any processor` warning (don't know if it's related to JDK 10). Because of this I've sadly needed to get back to per-mapper annotation option because I've spent almost to hours to get rid of this, without any success (only `-Xlint:none` works).

FYI: We need to have absolutely no warnings in the build process. Because we heavily use JDK serialization we need to ensure that each `Serializable` class has `serialVersionUID` field and we use warnings for that with `-Xlint:serial -Werror` options. So either first of second class of warnings related to mapstruct is harmful for us.

**Comment by filiphr** [comment]
If you don't see any MapStruct warnings with `-Amapstruct.unmappedTargetPolicy=IGNORE` then there is a processor that consumes that option 😄.

The problem you are seeing might be if you have a multi module project and you set that property for all modules, but you have the MapStruct compiler only for some modules. The other explanation would be that something has changed in JDK 10 and we are not marking that property as consumed, or the JDK 10 compiler has some bug,

**Comment by l0co** [comment]
That's interesting. I've extracted separate testcase and ... you're right. This problem is somehow related to our multi module project structure. However, the warning is shown for both kinds of submodules - these using mapstruct, and these not. We will try to dig into this.

@filiphr Thanks!

**Comment by filiphr** [comment]
@l0co I am not sure if you resolved your problem. However, I think that it might be related to https://github.com/mapstruct/mapstruct/issues/1638. You might want to look into the test compile outputting this as well.

I am going to close this issue for now as there is nothing that the plugin can do

**Comment by steklopod** [comment]
You can do like this:
```kotlin
@Mapper
interface CustomerConverter {
    @Mapping(source = "email", target = "nickname")
    fun toPersonDto(customer: Customer): CustomerDto

    @InheritInverseConfiguration
    @Mapping(target = "age", ignore = true)
    fun fromPersonDto(customerDto: CustomerDto): Customer
}
```
