### ISSUE TITLE
Auto-completion doesn't work in IDEA (version: 2017.2.5)

### ISSUE THREAD

**Issue by liamjung** [mapstruct/mapstruct-idea#22]
[issue.mov.zip](https://github.com/mapstruct/mapstruct-idea/files/1766670/issue.mov.zip)

**Comment by tmhpfnr** [comment]
@liamjung I guess you are using public fields which is not supported, only getters/setters see #16

**Comment by filiphr** [comment]
Just had a look at the video, it looks a bit weird, the `type` in the end is being correctly highlighted. @liamjung can you please share the entire `CarDto` and `Car` or point me in the place where they are located?

**Comment by filiphr** [comment]
Closing as there has been no feedback. If we get some feedback we can reopen it
