### ISSUE TITLE
Compiler warning in decorator

### ISSUE THREAD

**Issue by jordilaforge** [mapstruct/mapstruct-idea#27]
Hi There

I use the newest mapStruct 1.3.0.Beta2 in my project along with your mapStruct plugin for IntelliJ.  I use a mapStruct dercorator to do some post mapping stuff. Wenn using the plugin I see a compiler error  in the decorator class "@Mapper or @MapperConfig annotation missing...". But in the documentation of mapStruct is stated that there is no annotation needed in a decorator. (see http://mapstruct.org/documentation/stable/reference/html/#customizing-mappers-using-decorators)

Thank for the help

**Comment by filiphr** [comment]
The newest MapStruct is now [1.3.0.Final](http://mapstruct.org/news/2019-02-11-mapstruct-1_3_0_Final-is-out-in-the-wild/) 😉.  In any case that warning is shown when you are using `@Mapping` in a class or interface. Can you please give me an example of your decorator so I can have a better look?

**Comment by jordilaforge** [comment]
ok I have updated to the final version of mapstruct thanks. But the compiler Warning still persists. I have taken the lombok mapstruct example from github to reproduce the compiler error (https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok)
ok this is the mapper Inteface:
`@Mapper
@DecoratedWith(ConverterDecorator.class)
public interface Converter {

    Converter INSTANCE = Mappers.getMapper(Converter.class);

    @Mapping(source = "test1",target = "test2")
    Model fromDto(Dto dto);

    @Mapping(source = "test2",target = "test1")
    Dto toDto(Model model);
}`

**Comment by filiphr** [comment]
I see the problem now. Thanks for reporting the problem. I am going to have a look at it and fix it, this is clearly a bug.

**Comment by filiphr** [comment]
This has been fixed on master. Thanks for the reproducer @jordilaforge

**Comment by jearton** [comment]
I have the same problem. When to release?

**Comment by filiphr** [comment]
This was released on 16th of June as part of the 1.1.1 release
