### ISSUE TITLE
Compiler warning with a default method

### ISSUE THREAD

**Issue by jearton** [mapstruct/mapstruct-idea#31]
- mapstruct 1.2.0.Final
- mapstruct-idea 1.1.0

When I define a default method in the interface, the warning message as following will be shown.

```
Unmapped target properties: xxx
```

**Comment by jearton** [comment]
Just like this example: http://mapstruct.org/documentation/dev/reference/html/#adding-custom-methods

**Comment by filiphr** [comment]
This is normal behaviour of MapStruct the warning is from the Java compiler and has nothing to do with the IntelliJ plugin.

Have a look at [Mapper#unmappedTargetPolicy](http://mapstruct.org/documentation/stable/api/org/mapstruct/Mapper.html#unmappedTargetPolicy--_ for more information

**Comment by jearton** [comment]
@filiphr The warning message is not from the Java compiler. It only be shown by the inspection of IntelliJ Idea. This case should not be a warnning in MapStruct.

<img width="1096" alt="图片" src="https://user-images.githubusercontent.com/10370433/57208852-75ce1480-7008-11e9-8b1e-3d605d747caa.png">

<img width="683" alt="图片" src="https://user-images.githubusercontent.com/10370433/57208917-d3626100-7008-11e9-84db-898fa12d4b02.png">

**Comment by jearton** [comment]
@filiphr In the default method is hand-written mapping logic. No code will be generated.

**Comment by filiphr** [comment]
You are right @jearton, I missed the default method part.
