### ISSUE TITLE
unmapped target property with custom method in mapper

### ISSUE THREAD

**Issue by drej1** [mapstruct/mapstruct-idea#34]
Hi, 
I have the following mapper method:
```java
@Mapping(target = "name", ignore = true)
default CategoryRef mapProductCategoriesEnumToCateforyRef(ProductCategoriesEnum productCategoriesEnum){
    return new CategoryRef().id(productCategoriesEnum.toString());
}
```
while `CategoryRef` has 2 fields `id` and `name`. We ignore `name` via annotation and map only `id` manually as you can see in the code.

In this case we have a warning `Unmapped target property: id`. We actually map the `id` so why is it necessary to add annotation to ignore `id` too?
It seems weird to add it there while it is actually mapped.

Thanks.

**Comment by drej1** [comment]
Hi @filiphr , Can you confirm that this bug is the same as https://github.com/mapstruct/mapstruct-idea/issues/31 ? 
It looks that after plugin update we don't get the warning.
But it is intended that after the fix also if I remove `@Mapping(target = "name", ignore = true)` it doesn't warn that `name` is not mapped.

**Comment by filiphr** [comment]
@drej1 yes this issue is the same as #31. By mistake we were checking all methods. Since 1.1.1 from the plugin we are only checking abstract methods. 

Please let me know if removing the `@Mapping` doesn't work with the latest version of the plugin.
