### ISSUE TITLE
Mapping of Enum with public static method false Unmapped target property warning 

### ISSUE THREAD

**Issue by drej1** [mapstruct/mapstruct-idea#38]
Hi,

I have a mapping from source enum to target. My target enum looks like this:
```java
public enum AccountTypeEnum {
    CUSTOMER("customer"),
    
    BILLING("billing"),
    
    SERVICE("service"),
    
    HOUSEHOLD("household");

    private String value;

    AccountTypeEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AccountTypeEnum fromValue(String text) {
      for (AccountTypeEnum b : AccountTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
```

The problem is, that I get a warning: `Unmapped target property: fromValue` while it is a public static method and not a property.
I get this warning only in the mapstruct-idea plugin. Mapstruct itself doesn't give this warning while compilation.

**Comment by filiphr** [comment]
Thanks for raising this issue @drej1. We've fixed this on master with https://github.com/mapstruct/mapstruct-idea/commit/a0ed5e2c4db550d086cc78bd0716d0066d216323

**Comment by drej1** [comment]
@filiphr  thanks. We will test it when 1.2 will be out
