### ISSUE TITLE
Incorrect "unwrapped target property" warning for constant

### ISSUE THREAD

**Issue by wenbinye** [mapstruct/mapstruct-idea#47]
The mapping target class has some constant declare as :

```java
public class ReplenishProduct {
    public static final String EMPTY_STRING = "";
}
```

the mapping function highlight with warning:
<img width="758" alt="图片" src="https://user-images.githubusercontent.com/1221975/84474958-5222d680-acbe-11ea-9757-1adfdd81814b.png">

**Comment by filiphr** [comment]
Thanks for the issue. This has been fixed on master and will be part of the next release
