### ISSUE TITLE
Quick fix for Mapping - change the order of target and source

### ISSUE THREAD

**Issue by mkrumpholz** [mapstruct/mapstruct-idea#51]
when using the quick fix it adds the Mapping annotation with the target first and source second. More readable would be other way around, at least my opinion. Best way would be a configuration for this in the IDEA settings. :-)

**Comment by filiphr** [comment]
What is more readable is extremely questionable :). This is really a subjective taste. Having a way to configure this makes sense. Do you perhaps have experience with IDEA plugin settings and are willing to help out for this?

**Comment by mkrumpholz** [comment]
Yes, i do have that experience from my past plugins. But time is the problem... :disappointed:
