### ISSUE TITLE
idea plugins question

### ISSUE THREAD

**Issue by 1360100183** [mapstruct/mapstruct-idea#55]
idea plugins 

config
  idea version 2020.2
  mapstruct 13.1.Final
  gradle 6.+

describe
  I converted the implementation of inheriting abstract class in mapper. When the plug-in compiles automatically, an error is reported and the file disappears 
 
 public abstract class CommonPO implements Serializable, Cloneable {}
 @Data public class TenantPO extends CommonPO {}
 @Data public class TenantDTO {} 
@Mapper
public interface TenantConvert { TenantPO tenantDTOToTenantPO(TenantDTO tenantDTO); }

**Comment by filiphr** [comment]
Please do not use the issue tracker for asking questions. If you have questions then please use StackOverflow and tag your questions with the mapstruct tag.

In this particular case we will need to know what your error is to be able to help you.
