### ISSUE TITLE
Wrong parameter inference with expression="java(...)"

### ISSUE THREAD

**Issue by Grogdunn** [mapstruct/mapstruct-idea#66]
```java
public class SomeDto {
    private String value;
   //getter
   //setter
}
public class SomeBo {
    private String value;
   //getter
   //setter
}

@Mapper
public abstract class SomeMapper {

   @Mapping(target = "value", expression="java( someCleverLogic(input) )")
   public abstract SomeDto from(SomeBo input);

   public String someCleverLogic(String input){
      return "LoremIpsumDolor";
   }
}

// GENERATED
public class SomeMapperImpl extends SomeMapper {
   @Override
   public SomeDto from(SomeBo arg0){
      SomeDto someDto = new SomeDto();
      someDto.setValue(someCleverLogic(input));  //ERROR: cannot find symbol input!!!! 
      return someDto;
   }

}

```
With Idea maven builder + Mapstruct plugin sometimes a bunch of mappers like above lead to a wrong generated mapper implementation. The input param changes to arg0 while java expression continue using original name.

**Comment by filiphr** [comment]
The MapStruct IDEA plugin has no influence on how the code is generated, it is there only to help you in the annotations.

Looking at your generated code, I have no idea how it is possible to generate `arg0` when the `SomeMapper` is present in the same compilation.

I would suggest reviewing your maven setup, the generated code should use the same variables as your definitions.

**Comment by Grogdunn** [comment]
Ok, maybe some strange behavior of idea bundeled maven compliler.

Thanks for the answer.

**Comment by cnockemann** [comment]
We have exactly the same problem.
It doesn't seem to be a maven thing, because we use Gradle.
