### ISSUE TITLE
Support for Mapstruct explicit Builder disable

### ISSUE THREAD

**Issue by miclefebvre** [mapstruct/mapstruct-idea#67]
Using lombok @Builder with some @Singular properties shows warning of unmapped properties in the Intellij plugin.
Ex: If I have a property named baskets and singular, a new property basket is available in the builder and the plugin is saying it needs to be mapped.

Even, disabling the builder, the plugin continue to show warning :builder = @org.mapstruct.Builder(disableBuilder = true)

**Comment by filiphr** [comment]
Seems like this is an issue for the IntelliJ plugin.

Can you please provide a code with which we can reproduce the issue?

**Comment by miclefebvre** [comment]
Here an example. There's a warning saying unmapped property example (examples is correctly mapped, but there's another property example in the builder because of the @singular)

(Note: I did everything in an inner class for ease of testing, but it does the same thing without the inner class.

```
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Example {
	@Singular private List<ExampleDto> addresses;

	@Mapper(builder = @org.mapstruct.Builder(disableBuilder = true))
	public interface ExampleMapper {
		ExampleMapper INSTANCE = Mappers.getMapper( ExampleMapper.class );

		Example convert(Example example);
	}

	@Data
	@NoArgsConstructor
	@AllArgsConstructor
	@Builder
	public static class ExampleDto {
		private String name;
	}
}
```

**Comment by filiphr** [comment]
@miclefebvre I've changed the title of this issue since the plugin does not support the MapStruct `Builder#disable` currently. Therefore, you have that problem with Lombok.
