### ISSUE TITLE
Add code completion for @BeanMapping#ignoreUnmappedSourceProperties

### ISSUE THREAD

**Issue by daniel-shuy** [mapstruct/mapstruct-idea#77]
When [MapperConfig#unmappedSourcePolicy](https://mapstruct.org/documentation/stable/api/org/mapstruct/MapperConfig.html#unmappedSourcePolicy--) is set to [WARN/ERROR](https://mapstruct.org/documentation/stable/api/org/mapstruct/ReportingPolicy.html) (aka "strict mode"), [@BeanMapping#ignoreUnmappedSourceProperties](https://mapstruct.org/documentation/stable/api/org/mapstruct/BeanMapping.html#ignoreUnmappedSourceProperties--) is used to ignore unmapped source properties (the same way `@Mapping#ignore` is used to ignore unmapped target properties).

It would be nice if there could be code completion for [@BeanMapping#ignoreUnmappedSourceProperties](https://mapstruct.org/documentation/stable/api/org/mapstruct/BeanMapping.html#ignoreUnmappedSourceProperties--) as well

**Comment by daniel-shuy** [comment]
@filiphr wow thanks so much for implementing this!

**Comment by filiphr** [comment]
And we just released a new version of the plugin with this included. Have fun using it.
