### ISSUE TITLE
Publish to intellij repo

### ISSUE THREAD

**Issue by thekalinga** [mapstruct/mapstruct-idea#8]
Hi

Thanks for the plugin. It would be much useful for everyone if this plugin can be pushed to the intellij repo instead of manual builds by everyone

**Comment by filiphr** [comment]
@thekalinga You have started using it? That is great, how do you like it? Do you have some suggestions?

I am planning to do this really soon, we just need to setup the account so we can do it. I hope I would be able to do by the end of next week.

**Comment by filiphr** [comment]
@thekalinga the plugin has been published to the Jetbrains repo. 

[Here](http://mapstruct.org/news/2017-09-19-announcing-mapstruct-idea/) the announcement post and [here](https://plugins.jetbrains.com/plugin/10036-mapstruct-support) the link to the plugin.

Feel free to post feedback and open issues for what you want to see 😄

**Comment by thekalinga** [comment]
Thanks :)
