### ISSUE TITLE
Plugin fatal crush in case using static constant in target field of @Mapping annotation

### ISSUE THREAD

**Issue by promanovsky** [mapstruct/mapstruct-idea#88]
I have two interfaces 
1) First one with some static constants

```java
public interface CommonNsiMapper {

    String OKATO_CODE = "okato";
    String FULL_NAME_CODE = "fullName";
    String SHORT_NAME_CODE = "shortName";
    String RUSSIAN_NAME_CODE = "russianName";
    String DIFFERENCE_TIME_CODE = "differenceTime";
    String ADDRESS_CODE = "adress";
    String ASSEMBLY_ALGORITHM_CODE = "assemblyAlgorithm";
    String NORMA_LEGAL_DOC = "normaLegalDocument";

    default String mapStringFromAdditionalField(EtpNsiItem item, String code) {
        return item != null && item.getAdditionalFields() != null ? item.getAdditionalFields().get(code) : null;
    }

    default Integer mapIntegerFromAdditionalField(EtpNsiItem content, String code) {
        return StringUtils.isNotEmpty(content.getAdditionalFields().get(code)) ? Integer.getInteger(content.getAdditionalFields().get(code)) : null;
    }
}
```

2) Second one is using some constants for target field in Mapping annotations.
```java
@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE,
        uses = {BiddingRelationsMapper.class},
        config = BaseNsiMapper.class)
public interface ContractRefusalReasonNsiMapper extends CommonNsiMapper {

    @InheritConfiguration(name = "mapToNsiDto")
    @Mapping(target = "biddingRelation", source = "biddingRelations")
    @Mapping(target = NORMA_LEGAL_DOC, expression = "java(this.mapStringFromAdditionalField(content.getNsiItem(), NORMA_LEGAL_DOC))")
    ContractRefusalReason mapToExport(MasterDataItemContent content);
}
```

Every time when i open interfaces like 2 - i had a fatal plugin error (file with trace attached) [plugin_trace.log](https://github.com/mapstruct/mapstruct-idea/files/7634885/plugin_trace.log)

**Comment by promanovsky** [comment]
IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021

Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Registry:
    debugger.watches.in.variables=false
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.27.0)
    org.sonarlint.idea (6.3.0.39716)
    org.mapstruct.intellij (1.3.0)
    com.intellij.selenium (213.5744.172)
    Pythonid (213.5744.223)
    com.intellij.aspectj (213.5744.125)

Kotlin: 213-1.5.10-release-949-IJ5744.223

**Comment by filiphr** [comment]
Thanks for reporting this @promanovsky. We've managed to find the problem and are working on a fix for this.
